<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="cylinder_radius" value="0.03" /> 
    <xacro:property name="cylinder_lenght" value="0.3" />
    <xacro:property name="small_cylinder_radius" value="0.02" />
    <xacro:property name="small_cylinder_lenght" value="${cylinder_lenght}" />

    <xacro:property name="base_lenght" value="${mobile_l}" />
    <xacro:property name="base_width" value="${mobile_w}" />
    <xacro:property name="base_height" value="${mobile_h}" />
    <xacro:property name="base_xyz" value="0 0 0" />
    <xacro:property name="cylinder_rpy" value="0 0 0" />


    <!-- @@@@@@@@@@@@@@@@          Functions                @@@@@@@@@@@@@@@@ -->

    <xacro:macro name="create_cylinder_link" params="prefix">

    <link name="${prefix}_cylinder_link">
        <visual>
            <geometry>
                <cylinder radius="${cylinder_radius}" length="${cylinder_lenght}" />
            </geometry>
            <origin xyz="0 0 ${cylinder_lenght/2}" rpy="${cylinder_rpy}" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${cylinder_radius}" length="${cylinder_lenght}" />
            </geometry>
            <origin xyz="0 0 ${cylinder_lenght/2}" rpy="${cylinder_rpy}" />
        </collision>
        <xacro:cylinder_inertia mass="3.0" l="${2*cylinder_lenght}" r="${2*cylinder_radius}" xyz="0 0 ${cylinder_lenght/2}" rpy="${cylinder_rpy}" />
    </link>

    </xacro:macro> 

    <xacro:macro name="create_small_cylinder_link" params="prefix">

    <link name="${prefix}_small_cylinder_link">
        <visual>
            <geometry>
                <cylinder radius="${small_cylinder_radius}" length="${small_cylinder_lenght}" />
            </geometry>
            <origin xyz="0 0 ${-small_cylinder_lenght/2}" rpy="${cylinder_rpy}" />
            <material name="yellow" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${small_cylinder_radius}" length="${small_cylinder_lenght}" />
            </geometry>
            <origin xyz="0 0 ${-small_cylinder_lenght/2}" rpy="${cylinder_rpy}" />
        </collision>
        <!-- <self_collision>true</self_collision> -->
        <xacro:cylinder_inertia mass="1.5" l="${2*small_cylinder_lenght}" r="${2*small_cylinder_radius}" xyz="0 0 ${-small_cylinder_lenght/2}" rpy="${cylinder_rpy}" />
    </link>

    </xacro:macro>

    <!-- prismatic joint func -->

    <xacro:macro name="create_prismatic_joint" params="prefix parent child">

    <joint name="${prefix}_prismatic_joint" type="prismatic">
        <parent link="${parent}" />
        <child link="${child}" />
        <origin xyz="0 0 ${small_cylinder_lenght}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit lower="0" upper="${cylinder_lenght*0.8}" effort="1000.0" velocity="1.0"/>
        <dynamics damping="0.1" friction="0.01" />
    </joint>

    </xacro:macro>

    <!-- @@@@@@@@@@@@@@@@          Robot Creation                @@@@@@@@@@@@@@@@ -->

    <!-- Body -->

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="${base_xyz}" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="${base_xyz}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia mass="25.0" l="${2*base_lenght}" w="${2*base_width}" h="${2*base_height}" xyz="${base_xyz}" rpy="0 0 0" />
    </link>

    <!-- Connecting the base to balance robot to the mobile robot -->
    <joint name="mobile_base_joint" type="fixed">
        <parent link="mobile_base_link" />
        <child link="base_link" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <!-- Cylinders creations -->

    <xacro:create_cylinder_link prefix="front" />

    <joint name="front_cylinder_joint" type="fixed">
        <parent link="base_link" />
        <child link="front_cylinder_link" />
        <origin xyz="${(base_lenght / 2)} 0 ${(base_height / 2)}" rpy="0 0 0" />
        <!-- <dynamics damping="10.0" friction="10.0" /> that's actually a lot prettyh sure -->
    </joint>

    <xacro:create_cylinder_link prefix="right" />

    <joint name="right_cylinder_joint" type="fixed">
        <parent link="base_link" />
        <child link="right_cylinder_link" />
        <origin xyz="${-(base_lenght / 2)} ${-(base_width / 2)} ${(base_height / 2)}" rpy="0 0 0" />
    </joint>

    <xacro:create_cylinder_link prefix="left" />

    <joint name="left_cylinder_joint" type="fixed">
        <parent link="base_link" />
        <child link="left_cylinder_link" />
        <origin xyz="${-(base_lenght / 2)} ${(base_width / 2)} ${(base_height / 2)}" rpy="0 0 0" />
    </joint>

    <!-- Prismatic link/joints creation -->

    <xacro:create_small_cylinder_link prefix="front" />

    <xacro:create_small_cylinder_link prefix="left" />

    <xacro:create_small_cylinder_link prefix="right" />

    <xacro:create_prismatic_joint prefix="front" parent="front_cylinder_link" child="front_small_cylinder_link"/>  

    <xacro:create_prismatic_joint prefix="left" parent="left_cylinder_link" child="left_small_cylinder_link"/>  

    <xacro:create_prismatic_joint prefix="right" parent="right_cylinder_link" child="right_small_cylinder_link"/>

    <!-- <link name="platform_link">
        <visual>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_height / 4.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_height / 4.0}" />
            </geometry>
            <origin xyz="${base_xyz}" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia mass="25.0" l="${2*base_lenght}" w="${2*base_width}" h="${2*(base_height / 4.0)}" xyz="0 0 0" rpy="0 0 0" />
    </link>
    
    <joint name="platform_joint" type="floating">
        <parent link="front_small_cylinder_link" />
        <child link="platform_link" />
        <origin xyz="${-(base_lenght / 2)} 0 0" rpy="0 0 0" />
        <limit effort="100" velocity="100" />
    </joint> -->

</robot>
