<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- <xacro:property name="camera_l" value="0.01" />
    <xacro:property name="camera_w" value="0.1" />
    <xacro:property name="camera_h" value="0.05" />

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_l} ${camera_w} ${camera_h}" />
            </geometry>
            <material name="red" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_l} ${camera_w} ${camera_h}" />
            </geometry>
        </collision>
        <xacro:box_inertia mass="0.1" l="${camera_l}" w="${camera_w}" h="${camera_h}" xyz="0 0 0" rpy="0 0 0" />
    </link>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${(base_lenght + camera_l) / 2.0} 0 ${base_height - (camera_h / 2.0)}" rpy="0 0 0" />
    </joint>

    <link name="camera_link_optical" />

    <joint name="camera_optical_joint" type="fixed">
    
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    <parent link="camera_link"/>
    <child link="camera_link_optical"/> -->
    </joint> <!-- these values have to be these values otherwise the gazebo camera
        image won't be aligned properly with the frame it is supposedly
        originating from -->

    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        <sensor name="camera_sensor" type="depth">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10.0</update_rate>
            <camera>
                <!-- <horizontal_fov>1.089</horizontal_fov> -->  <!-- not sure what's the default -->
                <image>
                    <format>B8G8R8</format> <!-- instead ofthe default for the non depth camera which is R8G8B8 -->
                    <width>320</width>     <!-- default is 320 --> <!-- recent change = 640 -->
                    <height>240</height>   <!-- default is 240 --> <!-- recent change = 480 -->
                </image>
            </camera>
            <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                <frame_name>camera_link_optical</frame_name>
            </plugin>
        </sensor>
    </gazebo>

</robot>